<a href="https://colab.research.google.com/github/23aswathy/paatshala/blob/main/Virtual_competition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#importing the train data set

In [6]:
from google.colab import files
files.upload()

Saving train_ctrUa4K.csv to train_ctrUa4K.csv


{'train_ctrUa4K.csv': b'Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status\r\nLP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y\r\nLP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N\r\nLP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y\r\nLP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y\r\nLP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y\r\nLP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y\r\nLP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y\r\nLP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N\r\nLP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y\r\nLP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N\r\nLP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y\r\nLP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y\r\nLP001028,Male,Yes,2,Graduate,No,3073,8106,200,360,1,Urb

In [7]:
train_data=pd.read_csv('train_ctrUa4K.csv')

In [ ]:
train_data.head()

In [ ]:
#importing test data set

In [ ]:
from google.colab import files
files.upload()

Saving test_lAUu6dG.csv to test_lAUu6dG.csv


{'test_lAUu6dG.csv': b'Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area\r\nLP001015,Male,Yes,0,Graduate,No,5720,0,110,360,1,Urban\r\nLP001022,Male,Yes,1,Graduate,No,3076,1500,126,360,1,Urban\r\nLP001031,Male,Yes,2,Graduate,No,5000,1800,208,360,1,Urban\r\nLP001035,Male,Yes,2,Graduate,No,2340,2546,100,360,,Urban\r\nLP001051,Male,No,0,Not Graduate,No,3276,0,78,360,1,Urban\r\nLP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152,360,1,Urban\r\nLP001055,Female,No,1,Not Graduate,No,2226,0,59,360,1,Semiurban\r\nLP001056,Male,Yes,2,Not Graduate,No,3881,0,147,360,0,Rural\r\nLP001059,Male,Yes,2,Graduate,,13633,0,280,240,1,Urban\r\nLP001067,Male,No,0,Not Graduate,No,2400,2400,123,360,1,Semiurban\r\nLP001078,Male,No,0,Not Graduate,No,3091,0,90,360,1,Urban\r\nLP001082,Male,Yes,1,Graduate,,2185,1516,162,360,1,Semiurban\r\nLP001083,Male,No,3+,Graduate,No,4166,0,40,180,,Urban\r\nLP001094,Male,Yes,2,Graduat

In [9]:
test_data=pd.read_csv('test_lAUu6dG.csv')

In [60]:
test_data.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [ ]:
#finding the size of the train and test data sets

In [10]:
train_data.shape

(614, 13)

In [11]:
test_data.shape

(367, 12)

In [12]:
tr=train_data.copy()

In [13]:
ts=test_data.copy()

In [ ]:
#finding the null values in the training data set

In [14]:
tr.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [15]:
tr.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [16]:
tr.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [17]:
ts.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [ ]:
#filling the missing categorical fetures using mode and numerical features using median

In [18]:
for i in ['Loan_ID', 'Gender', 'Married','Dependents', 'Education','Self_Employed']:
  tr[i]=tr[i].fillna(tr[i].mode()[0])

In [19]:
tr.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [20]:
for i in ['LoanAmount','Loan_Amount_Term', 'Credit_History']:
  tr[i]=tr[i].fillna(tr[i].median())

In [21]:
tr.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [22]:
for i in ['Loan_ID', 'Gender', 'Married','Dependents', 'Education','Self_Employed']:
  ts[i]=ts[i].fillna(ts[i].mode()[0])

In [23]:
for i in ['LoanAmount','Loan_Amount_Term', 'Credit_History']:
  ts[i]=ts[i].fillna(ts[i].median())

In [24]:
ts.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [25]:
y=tr['Loan_Status']

In [26]:
X=tr.drop('Loan_Status',axis=1)
X=pd.get_dummies(X)

In [ ]:
#Building the model

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [ ]:
#Classification using Decision Tree

In [28]:
from sklearn.tree import DecisionTreeClassifier
dt_clf=DecisionTreeClassifier()
model1=dt_clf.fit(X_train,y_train)

In [29]:
y_pred=dt_clf.predict(X_test)

In [ ]:
y_pred

array(['Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y'],
      dtype=object)

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[24, 30],
       [13, 87]])

In [ ]:
accuracy_score(y_test,y_pred)

0.7207792207792207

In [ ]:
#kNN Classification


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
metric_k=[]
neighbors=np.arange(3,15)

In [ ]:
for k in neighbors:
  knn=KNeighborsClassifier(n_neighbors=k)

In [ ]:
model2=knn.fit(X_train,y_train)

In [ ]:
y_pred_knn=model2.predict(X_test)

In [ ]:
confusion_matrix(y_test,y_pred_knn)

array([[ 5, 49],
       [11, 89]])

In [ ]:
accuracy_score(y_test,y_pred_knn)

0.6103896103896104

In [30]:
#Random Forest Algorithm
from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier()

In [31]:
model3=rf_clf.fit(X_train,y_train)

In [32]:
y_pred_rf=model3.predict(X_test)

In [38]:
confusion_matrix(y_test,y_pred_rf)

array([[22, 32],
       [ 2, 98]])

In [39]:
accuracy_score(y_test,y_pred_rf)

0.7792207792207793

In [ ]:
#accuracy score of Decision tree Classifier=0.7207
#accuracy score of kNN Classifier=0.6103
#accuracy score of Random Forest Classifier=0.7792

In [ ]:
#From the classification models ,Random Forest Classification holds the best accuracy score and hence it is the best model for prediction.

In [ ]:
#Test data given to the Random Forest Classification model

In [40]:
ts=pd.get_dummies(ts)

In [41]:
X_test_data=ts

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test_data,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [43]:
from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier()

In [44]:
model3=rf_clf.fit(X_train,y_train)

In [45]:
y_pred_rf=model3.predict(X_test_data)

In [46]:
y_pred_rf

array(['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N',
       'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N'],
      dtype=object)

In [47]:
pred = pd.DataFrame(y_pred_rf,columns=['Loan_Status'])

In [48]:
pred

Loan_Status
0             Y
1             Y
2             Y
3             Y
4             Y
..          ...
149           Y
150           Y
151           Y
152           N
153           N

[154 rows x 1 columns]

In [49]:
X2=test_data['Loan_ID']

In [50]:
sample_out=pd.concat([X2,pred])

In [51]:
sample_out

0 Loan_Status
0    LP001015         NaN
1    LP001022         NaN
2    LP001031         NaN
3    LP001035         NaN
4    LP001051         NaN
..        ...         ...
149       NaN           Y
150       NaN           Y
151       NaN           Y
152       NaN           N
153       NaN           N

[521 rows x 2 columns]

In [52]:
out_pred=sample_out.rename(columns={0:'Loan_ID'})

In [53]:
out_pred

Loan_ID Loan_Status
0    LP001015         NaN
1    LP001022         NaN
2    LP001031         NaN
3    LP001035         NaN
4    LP001051         NaN
..        ...         ...
149       NaN           Y
150       NaN           Y
151       NaN           Y
152       NaN           N
153       NaN           N

[521 rows x 2 columns]

In [90]:
sample_out.to_csv("sample_submission_49d68Cx.csv",index=False)

In [87]:

sample_out.to_csv

<bound method NDFrame.to_csv of             0 Loan_Status
0    LP001015         NaN
1    LP001022         NaN
2    LP001031         NaN
3    LP001035         NaN
4    LP001051         NaN
..        ...         ...
149       NaN           Y
150       NaN           Y
151       NaN           Y
152       NaN           N
153       NaN           N

[521 rows x 2 columns]>